version: 2.0
jobs:
  build:
    working_directory: ~/app
    docker:
            - image: python:2.7-slim
    steps:
      - checkout # check out source code to working directory
      - run: mkdir test-results
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            sudo pip install -r requirements.txt
            sudo pip install unittest-xml-reporting
      - run:
          command: |
            python -m xmlrunner discover -s src/tests -t src/tests -o test-results
      - store_test_results: # Upload test results for display in Test Summary
          path: test-results
      - store_artifacts: # Upload test summary for display in Artifacts
          path: test-results
          destination: tr1
